version: 0.2

phases:
  install:
    commands:  # Install AWS cli, kubectl (needed for Helm) and Helm
      - apt-get update
      - apt install -y awscli git python3
      - curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.12.7/2019-03-27/bin/linux/amd64/aws-iam-authenticator
      - chmod +x ./aws-iam-authenticator
      - mkdir -p ~/bin && cp ./aws-iam-authenticator ~/bin/aws-iam-authenticator && export PATH=~/bin:$PATH
  pre_build:
    commands:
      - AWS_ACCOUNT_ID=705303224111
      - AWS_DEFAULT_REGION=eu-west-1
      - IMAGE_REPO_NAME=typegenie/typegenie-api-client
      - ENV=staging
      - aws --version
      - GITHUB_USER=renatomrochatg
      - ECR_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_URI
      - REPOSITORY_URI=$ECR_URI/$IMAGE_REPO_NAME
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG -f Production.Dockerfile .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$COMMIT_HASH
      - echo Will start running tests...
      - docker run -it $REPOSITORY_URI:$IMAGE_TAG python tests.py
  post_build:
    commands:
      - echo Build completed on `date`
      -|
      if [ "$CODEBUILD_BUILD_SUCCEEDING" == 1 ]; then
        docker run -v $(pwd):/root/TypeGenieAPIClient version-bumper-test:latest git remote set-url origin https://$GITHUB_USER:$OAUTH_TOKEN@github.com/abhitopia/TypeGenieAPIClient.git
        docker run -v $(pwd):/root/TypeGenieAPIClient version-bumper-test:latest bumpversion --current-version $CURRENT_TG_CLI_VERSION patch setup.py
        docker run -v $(pwd):/root/TypeGenieAPIClient version-bumper-test:latest git add setup.py
        docker run -v $(pwd):/root/TypeGenieAPIClient version-bumper-test:latest git commit -m "Codebuild bumpversion"
#        docker run -v $(pwd):/root/TypeGenieAPIClient version-bumper-test:latest git tag staging-release-$IMAGE_TAG
        docker run -v $(pwd):/root/TypeGenieAPIClient version-bumper-test:latest git push
        echo Version successfully bumped
      else
        echo Unit tests did not pass... will not bump version
      fi


# The below needs to be completed by Omkar
#      - "helm upgrade -i <RELEASE_NAME> <PATH_TO_HELM_FILES> -f ./path/to/kubernetes/values/values.$ENV.yaml --set image.tag=$CODEBUILD_RESOLVED_SOURCE_VERSION"
