version: 0.2

env:
  git-credential-helper: yes

phases:
  install:
    commands:  # Install AWS cli, kubectl (needed for Helm) and Helm
      - apt-get update
      - apt install -y awscli git python3
      - pip install typegenie bumpversion
      - curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.12.7/2019-03-27/bin/linux/amd64/aws-iam-authenticator
      - chmod +x ./aws-iam-authenticator
      - mkdir -p ~/bin && cp ./aws-iam-authenticator ~/bin/aws-iam-authenticator && export PATH=~/bin:$PATH
  pre_build:
    commands:
      - AWS_ACCOUNT_ID=705303224111
      - AWS_DEFAULT_REGION=eu-west-1
      - IMAGE_REPO_NAME=typegenie/typegenie-api-client
      - aws --version
      - ECR_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_URI
      - REPOSITORY_URI=$ECR_URI/$IMAGE_REPO_NAME
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - CURRENT_TG_CLI_VERSION=$(echo $(pip list | grep typegenie) | awk -F" " '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t version-bumper-test:latest -f Production.Dockerfile .
      - docker build -t $REPOSITORY_URI:latest -f Tests.Dockerfile .
      - echo Will now tag image
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - echo Image tagged successfully
      - echo Twine username is $TWINE_USERNAME
      - echo Test var $TEST_VAR
  post_build:
    commands:
      - echo Will start running tests...
      - echo Typegenie current version is $CURRENT_TG_CLI_VERSION
      - docker run -v /TypegenieAPIClient:/root/TypeGenieAPIClient version-bumper-test:latest bumpversion --current-version $CURRENT_TG_CLI_VERSION patch setup.py
      - docker run -v /TypegenieAPIClient:/root/TypeGenieAPIClient version-bumper-test:latest git add setup.py
      - docker run -v /TypegenieAPIClient:/root/TypeGenieAPIClient version-bumper-test:latest git checkout cicd_integration
      - docker run -v /TypegenieAPIClient:/root/TypeGenieAPIClient version-bumper-test:latest git commit -m "Codebuild bumpversion"
      - docker run -v /TypegenieAPIClient:/root/TypeGenieAPIClient version-bumper-test:latest git push origin cicd_integration
      - echo Version successfully bumped

